name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  boinc_ref: 82d0a3731c743884b6e7a25d68c6558eca691635  # client release 7.20.2

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Cache BOINC libs
      id: cache-boinc
      uses: actions/cache@v3
      with:
        path: |
          boinc/libboinc.a
          boinc/version.h
          boinc/lib
          boinc/include
          boinc/api
        key: boinc-${{ runner.os }}-${{ env.boinc_ref }}

    - name: Checkout boinc
      if: steps.cache-boinc.outputs.cache-hit != 'true'
      uses: actions/checkout@v3
      with:
        repository: 'BOINC/boinc'
        ref: ${{ env.boinc_ref }}
        path: 'boinc'
        
    - name: Build boinc
      if: steps.cache-boinc.outputs.cache-hit != 'true'
      run: |
        cd boinc
        ./_autosetup && ./configure --disable-server --disable-client --disable-manager
        make
        
        
    - name: Checkout genefer22
      uses: actions/checkout@v3
      with: 
        path: 'genefer22'
        
    - name: Get dependencies
      run: sudo apt-get update && sudo apt-get install libgmp-dev ocl-icd-opencl-dev
      
    - name: make
      run: cd genefer22 && make -f Makefile_linux64
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: linux64_bins
        path: |
          genefer22/bin/genefer22*
