name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout boinc
      uses: actions/checkout@v3
      with:
        repository: 'BOINC/boinc'
        ref: '82d0a3731c743884b6e7a25d68c6558eca691635' # client release 7.20.2
        path: 'boinc'
    - name: Build boinc
      run: cd boinc && ./_autosetup && ./configure --disable-server --disable-client --disable-manager
        
    - name: Checkout genefer22
      uses: actions/checkout@v3
      with: 
        path: 'genefer22'
      
    - name: make
      run: pwd && ls -lah # make -f Makefile_linux64
